pipeline {
    agent any 
    environment {
        MAVEN_HOME = '/opt/maven' // Specify the path to the correct Maven installation
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('Complete') {
            steps {
                echo 'Completed'
            }
        }
        stage('Pipeline v2') {
            steps {
                echo 'Pipeline V2 added'
            }
        }
    }
}
